services:
  wandering-wyvern:
    image: ghcr.io/dhrmaes/wandering-wyvern:${IMAGE_TAG:-latest}
    container_name: wandering-wyvern
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - aspnet-data-protection:/root/.aspnet/DataProtection-Keys

volumes:
  aspnet-data-protection:
